import {
  Company,
  Customer,
  Supplier,
  ProductGroup,
  ProductSubgroup,
  Product,
  User,
  SystemSettings,
  CashRegister,
  Sale,
  Order,
  AccountReceivable,
  AccountPayable,
  AuditLog,
  StockMovement,
} from '../types';

export const initialCompany: Company = {
  id: 'comp_1',
  name: 'Mini IERP Comércio e Serviços Ltda',
  tradeName: 'JG_IERP Mini Comércio',
  cnpj: '12.345.678/0001-90',
  stateRegistration: '123.456.789.110',
  phone: '(11) 3456-7890',
  whatsapp: '(11) 98765-4321',
  email: 'contato@jgierp.com.br',
  zipCode: '01310-100',
  street: 'Av. Paulista',
  number: '1000',
  complement: 'Sala 402',
  neighborhood: 'Bela Vista',
  city: 'São Paulo',
  state: 'SP',
};

export const initialSettings: SystemSettings = {
  defaultPrintFormat: 'A4',
  autoPrintSale: false,
  autoPrintOrder: false,
  printDuplicate: false,
  printReceipt: true,
  allowNegativeStock: false,
  footerMessage: 'Obrigado pela preferência! Volte sempre.',
  printCopies: 1,
  requireCashierForSale: true,
};

export const initialUsers: User[] = [
  {
    id: 'user_admin',
    name: 'Administrador do Sistema',
    login: 'admin',
    email: 'admin@jgierp.com.br',
    role: 'ADMINISTRADOR',
    status: 'ATIVO',
    permissions: [
      'view_product',
      'edit_product',
      'delete_product',
      'change_price',
      'give_discount',
      'cancel_sale',
      'open_cashier',
      'close_cashier',
      'view_finance',
      'delete_order',
      'manage_users',
      'manage_stock',
    ],
    lastLogin: '2026-10-07 09:15:00',
  },
  {
    id: 'user_gerente',
    name: 'Carlos Mendes',
    login: 'gerente',
    email: 'gerente@jgierp.com.br',
    role: 'GERENTE',
    status: 'ATIVO',
    permissions: [
      'view_product',
      'edit_product',
      'change_price',
      'give_discount',
      'cancel_sale',
      'open_cashier',
      'close_cashier',
      'view_finance',
      'manage_stock',
    ],
    lastLogin: '2026-10-07 08:30:00',
  },
  {
    id: 'user_caixa',
    name: 'Juliana Caixa',
    login: 'caixa',
    email: 'caixa@jgierp.com.br',
    role: 'CAIXA',
    status: 'ATIVO',
    permissions: [
      'view_product',
      'give_discount',
      'open_cashier',
      'close_cashier',
    ],
    lastLogin: '2026-10-07 08:00:00',
  },
  {
    id: 'user_vendedor',
    name: 'Roberto Vendas',
    login: 'vendedor',
    email: 'vendedor@jgierp.com.br',
    role: 'VENDEDOR',
    status: 'ATIVO',
    permissions: ['view_product'],
    lastLogin: '2026-10-06 17:00:00',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust_1',
    code: '001',
    name: 'João da Silva',
    tradeName: 'João da Silva',
    document: '12345678909',
    type: 'PF',
    rgIe: '12.345.678-9',
    phone: '11988887777',
    whatsapp: '11988887777',
    email: 'joao.silva@email.com',
    zipCode: '04001-000',
    street: 'Rua das Flores',
    number: '123',
    neighborhood: 'Paraíso',
    city: 'São Paulo',
    state: 'SP',
    notes: 'Cliente preferencial de balcão.',
    creditLimit: 1500,
    status: 'ATIVO',
    createdAt: '2026-01-15',
  },
  {
    id: 'cust_2',
    code: '002',
    name: 'Maria Oliveira',
    tradeName: 'Maria Silva Oliveira',
    document: '98765432100',
    type: 'PF',
    phone: '11977776666',
    whatsapp: '11977776666',
    email: 'maria.oliveira@email.com',
    zipCode: '05402-000',
    street: 'Rua Augusta',
    number: '450',
    neighborhood: 'Consolação',
    city: 'São Paulo',
    state: 'SP',
    creditLimit: 3000,
    status: 'ATIVO',
    createdAt: '2026-02-10',
  },
  {
    id: 'cust_3',
    code: '003',
    name: 'Empresa Teste LTDA',
    tradeName: 'Tech Teste Soluções',
    document: '45123987000155',
    type: 'PJ',
    rgIe: '987.654.321.000',
    phone: '1133334444',
    whatsapp: '11999990000',
    email: 'financeiro@empresateste.com.br',
    zipCode: '04543-000',
    street: 'Av. Brigadeiro Faria Lima',
    number: '2000',
    complement: 'Conjunto 81',
    neighborhood: 'Itaim Bibi',
    city: 'São Paulo',
    state: 'SP',
    notes: 'Faturamento a prazo em 15/30 dias.',
    creditLimit: 10000,
    status: 'ATIVO',
    createdAt: '2026-03-01',
  },
  {
    id: 'cust_consumer',
    code: '000',
    name: 'Consumidor Final',
    tradeName: 'Não Identificado',
    document: '00000000000',
    type: 'PF',
    phone: '',
    email: '',
    zipCode: '',
    street: '',
    number: '',
    neighborhood: '',
    city: 'São Paulo',
    state: 'SP',
    creditLimit: 0,
    status: 'ATIVO',
    createdAt: '2026-01-01',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup_1',
    code: '001',
    name: 'Distribuidora Alimentos Brasil S/A',
    tradeName: 'Alimentos Brasil',
    cnpj: '11222333000144',
    ie: '111.222.333.444',
    phone: '1134560000',
    email: 'pedidos@alimentosbrasil.com.br',
    city: 'São Paulo',
    state: 'SP',
    contactPerson: 'Fernando Dias',
    status: 'ATIVO',
  },
  {
    id: 'sup_2',
    code: '002',
    name: 'Bebidas Imperial Indústria Ltda',
    tradeName: 'Bebidas Imperial',
    cnpj: '22333444000155',
    phone: '1145678900',
    email: 'vendas@bebidasimperial.com.br',
    city: 'Campinas',
    state: 'SP',
    status: 'ATIVO',
  },
  {
    id: 'sup_3',
    code: '003',
    name: 'Limp Clean Produtos Químicos',
    tradeName: 'Limp Clean',
    cnpj: '33444555000166',
    phone: '1122223333',
    email: 'sac@limpclean.com.br',
    city: 'Guarulhos',
    state: 'SP',
    status: 'ATIVO',
  },
];

export const initialGroups: ProductGroup[] = [
  { id: 'grp_1', name: 'Alimentos', description: 'Gêneros alimentícios e secos' },
  { id: 'grp_2', name: 'Bebidas', description: 'Sucos, refrigerantes e água' },
  { id: 'grp_3', name: 'Limpeza', description: 'Produtos químicos e sanitários' },
  { id: 'grp_4', name: 'Eletrônicos', description: 'Acessórios e componentes' },
];

export const initialSubgroups: ProductSubgroup[] = [
  { id: 'sub_1', groupId: 'grp_1', name: 'Mercearia' },
  { id: 'sub_2', groupId: 'grp_1', name: 'Matinais' },
  { id: 'sub_3', groupId: 'grp_2', name: 'Refrigerantes' },
  { id: 'sub_4', groupId: 'grp_2', name: 'Sucos e Águas' },
  { id: 'sub_5', groupId: 'grp_3', name: 'Detergentes' },
  { id: 'sub_6', groupId: 'grp_4', name: 'Cabos e Conectores' },
];

export const initialProducts: Product[] = [
  {
    id: 'prod_1',
    code: '0001',
    barcode: '78910001',
    name: 'Produto A',
    description: 'Item padrão de demonstração para vendas e PDV',
    unit: 'UN',
    groupId: 'grp_1',
    groupName: 'Alimentos',
    subgroupId: 'sub_1',
    subgroupName: 'Mercearia',
    brand: 'Master Indústria',
    supplierId: 'sup_1',
    supplierName: 'Distribuidora Alimentos Brasil S/A',
    reference: 'REF-PA-01',
    ncm: '21069090',
    cest: '1700100',
    cfop: '5102',
    cst: '00',
    csosn: '102',
    costPrice: 12.0,
    salePrice: 25.0,
    minPrice: 22.0,
    currentStock: 48,
    minStock: 10,
    maxStock: 200,
    location: 'Corredor A - Prateleira 2',
    active: true,
  },
  {
    id: 'prod_2',
    code: '0002',
    barcode: '78910002',
    name: 'Produto B',
    description: 'Item secundário de alta rotatividade',
    unit: 'UN',
    groupId: 'grp_1',
    groupName: 'Alimentos',
    subgroupId: 'sub_1',
    subgroupName: 'Mercearia',
    brand: 'Master Indústria',
    supplierId: 'sup_1',
    supplierName: 'Distribuidora Alimentos Brasil S/A',
    reference: 'REF-PB-02',
    ncm: '19053100',
    cfop: '5102',
    costPrice: 7.5,
    salePrice: 15.0,
    minPrice: 13.5,
    currentStock: 79,
    minStock: 15,
    maxStock: 150,
    location: 'Corredor A - Prateleira 3',
    active: true,
  },
  {
    id: 'prod_3',
    code: '0003',
    barcode: '78910003',
    name: 'Produto C',
    description: 'Produto intermediário linha premium',
    unit: 'UN',
    groupId: 'grp_2',
    groupName: 'Bebidas',
    subgroupId: 'sub_4',
    subgroupName: 'Sucos e Águas',
    brand: 'Imperial',
    supplierId: 'sup_2',
    supplierName: 'Bebidas Imperial Indústria Ltda',
    reference: 'REF-PC-03',
    ncm: '22021000',
    cfop: '5102',
    costPrice: 20.0,
    salePrice: 42.0,
    minPrice: 38.0,
    currentStock: 30,
    minStock: 8,
    maxStock: 80,
    location: 'Corredor B - Geladeira 1',
    active: true,
  },
  {
    id: 'prod_4',
    code: '0004',
    barcode: '78910004',
    name: 'Produto D',
    description: 'Componente eletrônico com garantia',
    unit: 'UN',
    groupId: 'grp_4',
    groupName: 'Eletrônicos',
    subgroupId: 'sub_6',
    subgroupName: 'Cabos e Conectores',
    brand: 'TechLink',
    reference: 'REF-PD-04',
    ncm: '85444200',
    cfop: '5102',
    costPrice: 45.0,
    salePrice: 89.9,
    minPrice: 80.0,
    currentStock: 15,
    minStock: 5,
    maxStock: 50,
    location: 'Balcão Vitrine',
    active: true,
  },
  {
    id: 'prod_5',
    code: '0005',
    barcode: '78910005',
    name: 'Refrigerante Cola 2L',
    description: 'Garrafa Pet 2 Litros',
    unit: 'UN',
    groupId: 'grp_2',
    groupName: 'Bebidas',
    subgroupId: 'sub_3',
    subgroupName: 'Refrigerantes',
    brand: 'Imperial',
    supplierId: 'sup_2',
    supplierName: 'Bebidas Imperial Indústria Ltda',
    reference: 'REF-REFRI-2L',
    ncm: '22021000',
    cfop: '5102',
    costPrice: 4.8,
    salePrice: 9.5,
    minPrice: 8.5,
    currentStock: 64,
    minStock: 20,
    maxStock: 200,
    location: 'Depósito Central',
    active: true,
  },
  {
    id: 'prod_6',
    code: '0006',
    barcode: '78910006',
    name: 'Detergente Multiuso 500ml',
    description: 'Detergente neutro biodegradável',
    unit: 'UN',
    groupId: 'grp_3',
    groupName: 'Limpeza',
    subgroupId: 'sub_5',
    subgroupName: 'Detergentes',
    brand: 'Limp Clean',
    supplierId: 'sup_3',
    supplierName: 'Limp Clean Produtos Químicos',
    reference: 'REF-DET-500',
    ncm: '34022000',
    cfop: '5102',
    costPrice: 2.1,
    salePrice: 4.8,
    minPrice: 4.2,
    currentStock: 4, // Estoque baixo para acionar alerta
    minStock: 10,
    maxStock: 100,
    location: 'Prateleira Limpeza C',
    active: true,
  },
];

export const initialCashRegister: CashRegister = {
  id: 'cx_active_01',
  openingDate: '2026-10-07',
  openingTime: '08:00:00',
  openedByUserId: 'user_caixa',
  openedByUserName: 'Juliana Caixa',
  initialAmount: 200.0,
  cashSales: 150.0,
  pixSales: 210.0,
  debitSales: 95.0,
  creditSales: 180.0,
  otherSales: 0.0,
  bleedAmount: 50.0, // Sangria realizada
  supplyAmount: 0.0,
  expectedTotal: 300.0, // 200 inicial + 150 dinheiro - 50 sangria = 300
  status: 'ABERTO',
  notes: 'Caixa aberto no turno da manhã com suprimento inicial de R$ 200,00.',
};

export const initialSales: Sale[] = [
  {
    id: 'sale_000101',
    number: '000101',
    date: '2026-10-07',
    time: '08:35:12',
    customerId: 'cust_2',
    customerName: 'Maria Oliveira',
    customerDocument: '987.654.321-00',
    sellerId: 'user_caixa',
    sellerName: 'Juliana Caixa',
    subtotal: 104.9,
    discount: 4.9,
    addition: 0,
    total: 100.0,
    status: 'FINALIZADA',
    notes: 'Venda de balcão concluída com sucesso.',
    cashRegisterId: 'cx_active_01',
    items: [
      {
        id: 'item_101_1',
        productId: 'prod_4',
        code: '0004',
        barcode: '78910004',
        name: 'Produto D',
        unit: 'UN',
        quantity: 1,
        unitPrice: 89.9,
        discount: 0,
        total: 89.9,
      },
      {
        id: 'item_101_2',
        productId: 'prod_2',
        code: '0002',
        barcode: '78910002',
        name: 'Produto B',
        unit: 'UN',
        quantity: 1,
        unitPrice: 15.0,
        discount: 4.9,
        total: 10.1,
      },
    ],
    payments: [
      {
        id: 'pay_101_1',
        method: 'CARTAO_CREDITO',
        amount: 100.0,
        installments: 1,
      },
    ],
  },
  {
    id: 'sale_000102',
    number: '000102',
    date: '2026-10-07',
    time: '09:05:44',
    customerId: 'cust_consumer',
    customerName: 'Consumidor Final',
    sellerId: 'user_caixa',
    sellerName: 'Juliana Caixa',
    subtotal: 150.0,
    discount: 0,
    addition: 0,
    total: 150.0,
    status: 'FINALIZADA',
    cashRegisterId: 'cx_active_01',
    items: [
      {
        id: 'item_102_1',
        productId: 'prod_1',
        code: '0001',
        barcode: '78910001',
        name: 'Produto A',
        unit: 'UN',
        quantity: 6,
        unitPrice: 25.0,
        discount: 0,
        total: 150.0,
      },
    ],
    payments: [
      {
        id: 'pay_102_1',
        method: 'DINHEIRO',
        amount: 150.0,
      },
    ],
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord_000050',
    number: '000050',
    date: '2026-10-07',
    time: '08:45:00',
    customerId: 'cust_3',
    customerName: 'Empresa Teste LTDA',
    customerDocument: '45.123.987/0001-55',
    sellerId: 'user_gerente',
    sellerName: 'Carlos Mendes',
    subtotal: 500.0,
    discount: 25.0,
    addition: 0,
    total: 475.0,
    paymentMethodExpected: 'BOLETO',
    notes: 'Entrega programada para o período da tarde no escritório central.',
    status: 'SEPARACAO',
    items: [
      {
        id: 'ord_item_1',
        productId: 'prod_1',
        code: '0001',
        barcode: '78910001',
        name: 'Produto A',
        unit: 'UN',
        quantity: 20,
        unitPrice: 25.0,
        discount: 25.0,
        total: 475.0,
      },
    ],
  },
  {
    id: 'ord_000051',
    number: '000051',
    date: '2026-10-06',
    time: '14:20:00',
    customerId: 'cust_1',
    customerName: 'João da Silva',
    customerDocument: '123.456.789-09',
    sellerId: 'user_vendedor',
    sellerName: 'Roberto Vendas',
    subtotal: 125.0,
    discount: 5.0,
    addition: 0,
    total: 120.0,
    paymentMethodExpected: 'PIX',
    status: 'FINALIZADO',
    items: [
      {
        id: 'ord_item_2',
        productId: 'prod_1',
        code: '0001',
        barcode: '78910001',
        name: 'Produto A',
        unit: 'UN',
        quantity: 5,
        unitPrice: 25.0,
        discount: 5.0,
        total: 120.0,
      },
    ],
  },
];

export const initialReceivables: AccountReceivable[] = [
  {
    id: 'rec_1',
    customerId: 'cust_3',
    customerName: 'Empresa Teste LTDA',
    documentNumber: 'DOC-50-01',
    saleNumber: '000095',
    installmentNumber: 1,
    totalInstallments: 2,
    issueDate: '2026-09-20',
    dueDate: '2026-10-20',
    amount: 1250.0,
    paidAmount: 0,
    balance: 1250.0,
    status: 'PENDENTE',
    notes: 'Boleto bancário emitido via banco.',
  },
  {
    id: 'rec_2',
    customerId: 'cust_3',
    customerName: 'Empresa Teste LTDA',
    documentNumber: 'DOC-50-02',
    saleNumber: '000095',
    installmentNumber: 2,
    totalInstallments: 2,
    issueDate: '2026-09-20',
    dueDate: '2026-11-20',
    amount: 1250.0,
    paidAmount: 0,
    balance: 1250.0,
    status: 'PENDENTE',
  },
  {
    id: 'rec_3',
    customerId: 'cust_1',
    customerName: 'João da Silva',
    documentNumber: 'CRE-2026-08',
    saleNumber: '000088',
    installmentNumber: 1,
    totalInstallments: 1,
    issueDate: '2026-09-01',
    dueDate: '2026-10-01',
    amount: 180.0,
    paidAmount: 0,
    balance: 180.0,
    status: 'VENCIDO',
    notes: 'Conta vencida a receber em atraso.',
  },
];

export const initialPayables: AccountPayable[] = [
  {
    id: 'pay_1',
    supplierId: 'sup_1',
    supplierName: 'Distribuidora Alimentos Brasil S/A',
    documentNumber: 'NF-44910',
    category: 'Mercadorias para Revenda',
    issueDate: '2026-09-25',
    dueDate: '2026-10-15',
    amount: 1840.0,
    paidAmount: 0,
    balance: 1840.0,
    status: 'PENDENTE',
    notes: 'Reposição quinzenal de estoque.',
  },
  {
    id: 'pay_2',
    supplierId: 'sup_2',
    supplierName: 'Bebidas Imperial Indústria Ltda',
    documentNumber: 'NF-11204',
    category: 'Bebidas e Refrigerantes',
    issueDate: '2026-09-18',
    dueDate: '2026-10-05',
    amount: 650.0,
    paidAmount: 0,
    balance: 650.0,
    status: 'VENCIDO',
    notes: 'Aguardando liberação do financeiro.',
  },
];

export const initialStockMovements: StockMovement[] = [
  {
    id: 'mov_1',
    productId: 'prod_1',
    productName: 'Produto A',
    quantity: 50,
    type: 'ENTRADA',
    date: '2026-10-01',
    time: '10:00:00',
    userId: 'user_admin',
    userName: 'Administrador do Sistema',
    documentNumber: 'NF-44910',
    reason: 'Entrada por nota fiscal de compra',
  },
  {
    id: 'mov_2',
    productId: 'prod_2',
    productName: 'Produto B',
    quantity: 80,
    type: 'ENTRADA',
    date: '2026-10-01',
    time: '10:05:00',
    userId: 'user_admin',
    userName: 'Administrador do Sistema',
    documentNumber: 'NF-44910',
    reason: 'Entrada por nota fiscal de compra',
  },
  {
    id: 'mov_3',
    productId: 'prod_1',
    productName: 'Produto A',
    quantity: 2,
    type: 'VENDA',
    date: '2026-10-07',
    time: '08:35:12',
    userId: 'user_caixa',
    userName: 'Juliana Caixa',
    documentNumber: '000101',
    reason: 'Venda realizada no PDV',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'aud_1',
    date: '2026-10-07',
    time: '08:00:00',
    userId: 'user_caixa',
    userName: 'Juliana Caixa',
    action: 'ABERTURA DE CAIXA',
    entity: 'CAIXA',
    entityId: 'cx_active_01',
    details: 'Abertura de caixa com valor inicial de R$ 200,00',
  },
  {
    id: 'aud_2',
    date: '2026-10-07',
    time: '08:35:12',
    userId: 'user_caixa',
    userName: 'Juliana Caixa',
    action: 'VENDA FINALIZADA',
    entity: 'VENDA',
    entityId: '000101',
    details: 'Venda nº 000101 no valor total de R$ 100,00 para Maria Oliveira',
  },
  {
    id: 'aud_3',
    date: '2026-10-07',
    time: '09:05:44',
    userId: 'user_caixa',
    userName: 'Juliana Caixa',
    action: 'VENDA FINALIZADA',
    entity: 'VENDA',
    entityId: '000102',
    details: 'Venda nº 000102 no valor total de R$ 150,00 em Dinheiro para Consumidor Final',
  },
];
